<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="108916" started-at="2020-11-26T16:44:41 AEDT" finished-at="2020-11-26T16:46:30 AEDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="108916" started-at="2020-11-26T16:44:41 AEDT" finished-at="2020-11-26T16:46:30 AEDT">
      <class name="com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail">
        <test-method status="FAIL" signature="addHiveBrand()[pri:0, instance:com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail@ea1a8d5]" name="addHiveBrand" duration-ms="97221" started-at="2020-11-26T16:44:42 AEDT" finished-at="2020-11-26T16:46:19 AEDT">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Add Hive Brand Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Add Hive Brand Exception
at junit.framework.Assert.fail(Assert.java:47)
at com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail.addHiveBrand(UX_BeekeeperRegressionTestCasesTestRail.java:300)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addHiveBrand -->
        <test-method status="PASS" signature="addHiveLocationAddress()[pri:0, instance:com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail@ea1a8d5]" name="addHiveLocationAddress" duration-ms="108834" started-at="2020-11-26T16:44:42 AEDT" finished-at="2020-11-26T16:46:30 AEDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addHiveLocationAddress -->
        <test-method status="FAIL" signature="UpdateAccountDetailsAndPrimaryLocation()[pri:0, instance:com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail@ea1a8d5]" name="UpdateAccountDetailsAndPrimaryLocation" duration-ms="51885" started-at="2020-11-26T16:44:42 AEDT" finished-at="2020-11-26T16:45:33 AEDT">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[UpdateAccountDetailsAndPrimaryLocation Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: UpdateAccountDetailsAndPrimaryLocation Exception
at junit.framework.Assert.fail(Assert.java:47)
at com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail.UpdateAccountDetailsAndPrimaryLocation(UX_BeekeeperRegressionTestCasesTestRail.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateAccountDetailsAndPrimaryLocation -->
      </class> <!-- com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
